Add RWR pathway reconstruction algorithm
Reed-CompBio/spras pull request #148
Opened 2024-02-21 01:01 UTC by Lyce24

This pull request replaces the RWR part of pull request #92. Changes are made to adapt the updated version of SPRAS with directionality.

2024-03-06 19:53 UTC, annaritz requested changes
Some clarifications will be helpful, especially about:
1. The logic of sources/targets/prize files
2. What happens if there are no sources (or if there are no targets in the source-target mode)
3. Whether you want to have separate output files or keep all outputs in a single file.

2024-03-06 19:53 UTC, annaritz commented on spras/rwr.py
> +RWR will construct a directed graph from the provided input file
It's good to note that RWR assumes a directed graph. "From the provided input file" is vague, especially if the user can input a network file and a node prizes file.

2024-03-06 19:53 UTC, annaritz commented on spras/rwr.py
> +Expected raw input format:
What is edge flux for the input file requirements? And this is the network file, correct?

2024-03-06 19:53 UTC, annaritz commented on spras/rwr.py
> +Expected raw input format for prizes:
Is the prizes file optional, or is it required and your code will generate a stub file with all nodes set to 1.0? Also, I think the description here is for the network file, not the node file.

2024-03-06 19:53 UTC, annaritz commented on spras/rwr.py
> +Expected raw input format for prizes:
This file should be renamed to focus on sources/targets, with prizes as a secondary attribute. RWR requires at least sources to run, even if there are no targets or prizes, right?

2024-03-06 19:53 UTC, annaritz commented on spras/rwr.py
> +                sources_targets = data.request_node_columns(['prize'])
Here you are assuming that if there is NO sources file but there's a prize file, all the nodes with a prize are sources, right? Add comments to clearly descibe the logic here.

2024-03-06 19:53 UTC, annaritz commented on spras/rwr.py
> +        if sources_targets is None:
What happens if there are targets but no sources?

2024-03-06 19:53 UTC, annaritz commented on spras/rwr.py
> +                #If there aren't prizes but are sources and targets, make prizes based on them
Minor - rephrase to be "If there aren't prizes but there are sources and targets, set their prize to be 1.0"

2024-03-06 19:53 UTC, annaritz commented on spras/rwr.py
> +    def run(edges=None, prizes = None, output_file = None, single_source = None, df = None, w = None, f = None, threshold = None, container_framework="docker"):
Should single_source be a Boolean?

2024-03-06 19:53 UTC, annaritz commented on spras/rwr.py
> +        df_pathway = df.loc[df['Type'] == 3]
I'm confused about that Type 3 is. Is this the subgraph after filtering applying the selection function and threshold? A few more comments here (or at the top) about these output types would be helpful.

2024-03-06 19:53 UTC, annaritz commented on test/RWR/test_rwr.py
> +OUT_FILE_OPTIONAL = TEST_DIR+'output/rwr-edges-optional.txt'
Rename OPTIONAL to OPTIONS or OPTIONAL_ARGS - I think that's what you mean (the optional arguments)

2024-03-06 19:53 UTC, annaritz commented on spras/rwr.py
> +    def parse_output(raw_pathway_file, standardized_pathway_file):
I now remember that we talked about how your RWR outputs everything as a single file, so you can parse pieces of it in `parse_output()`. Would you rather output three separate output files? That would be cleaner conceptually. We can ask the group about how to parse multiple output files.

2025-06-12 21:13 UTC, tristan-f-r commented
Superseded by #261.

2025-06-12 21:13 UTC, closed without merging