Contributing Guide check-in
Reed-CompBio/spras pull request #159
Opened 2024-06-10 16:27 UTC by gabeah

Ready for overview by supervisors

2024-06-10 19:04 UTC, annaritz requested changes
Some minor comments after 6/10 code review.

2024-06-10 19:04 UTC, annaritz commented on test/generate-inputs/expected/local_neighborhood-network-expected.txt.txt
> +A|B
remove one of the `.txt`s

2024-06-11 16:44 UTC, gabeah commented on spras/local_neighborhood.py
> +        work_dir = '/spras'
keeping as-is until we get an answer from @agitter

2024-06-13 22:26 UTC, annaritz commented on spras/local_neighborhood.py
> +        work_dir = '/spras'
This is fine - something to clarify when we modify the Contributing Guide text.

2024-06-13 22:27 UTC, annaritz approved these changes

2024-06-13 22:28 UTC, annaritz commented
Looks good @gabeah - will close this as done.

2024-06-13 22:28 UTC, closed without merging