Post processing / ML Codde  - Aggregate per algorithm
Reed-CompBio/spras pull request #160
Opened 2024-06-10 19:57 UTC by ntalluri

2024-06-10 20:18 UTC, ntalluri commented
Failed due to ML Bug https://github.com/Reed-CompBio/spras/pull/143

2024-06-14 14:00 UTC, agitter reviewed
I merged the changes from #143 and left some high level comments before reviewing the code in detail.

2024-06-14 14:00 UTC, agitter commented on config/config.yaml
> +        # required; adds ml analysis per algorithm output
Maybe this should be optional and default to false?

I haven't looked through the code line-by-line yet. Is the behavior that if this is true, we will get the overall summaries as before and then additionally compute these algorithm-specified summaries? That is what I would expect.

2024-06-14 14:15 UTC, agitter commented
We may need to think more about the errors we added in #143 when there are not enough pathways for the ML analysis. Now that we can aggregate by algorithm, that will be a common occurrence. Some algorithms don't have parameters so there will always be a single pathway generated. Should we inspect the number of parameter combinations in the config file and only try running ML analysis for those algorithms with multiple parameter combinations?

2024-06-14 16:36 UTC, ntalluri commented
Would the snake make command --keep-going be sufficient enough and allow the error to be printed out to the command line?

2024-06-14 22:26 UTC, agitter commented
> Would the snake make command --keep-going be sufficient enough

I would rather not require users to add another argument to Snakemake at the command line in order to successfully execute fairly common configurations. It seems like it would lead to a lot of confusion if forgetting that option causes the workflow to crash, so if we can figure out a strategy for writing default outputs or avoiding calling the per-algorithm aggregation when it won't work, that would be better.

2024-06-17 15:04 UTC, ntalluri commented
I updated the Snakemake workflow to only run for algorithms that are using multiple parameters when it comes to ml-aggregate

2024-06-23 02:11 UTC, agitter requested changes
There are two types of end-to-end integration tests that would be nice to have, but we aren't set up well to make those kinds of tests currently. They would require running the entire workflow. Those tests:
- given the config file `config.yaml`, confirm that only the expected algorithms produce ensemble files
- confirm that one of the expected algorithm-specific ensembles (e.g. `data1-ml/omicsintegrator1-ensemble-pathway.txt`) is correct

Are these tests too hard in our current framework?

This design is great. I confirmed that if I add another parameter combination to the config file for MEO and then rerun Snakemake, then an ensemble pathway and ML outputs are created for MEO.

2024-06-23 02:11 UTC, agitter commented on config/config.yaml
> +        # works only on algorithms with multiple parameter combinations chosen
```suggestion
        # only runs for algorithms with multiple parameter combinations chosen
        # default value false if not set
```

2024-06-29 20:03 UTC, agitter commented on Snakefile
> +        ml.ensemble_network(summary_df, output.ensemble_network_file)
We're saving this for #165

2024-06-29 20:08 UTC, agitter approved these changes

2024-06-29 20:08 UTC, merged