Container workflow overhaul
Reed-CompBio/spras pull request #198
Opened 2024-12-09 18:17 UTC by jhiemstrawisc

This PR overhauls some of the GHA workflows designed to build spras's docker containers. In particular, it defines a new template in `.github/workflows/build-and-remove-template.yml` that tries to accomplish the following:
- Only build containers when they've been modified -- no need to build every container if their definitions haven't changed
- Split out the container build workflow so it can happen if needed in parallel to other tests.
- Update the docker build/push action to use the @v6 tag.

2025-01-18 03:35 UTC, agitter requested changes
This new design is excellent. The only non-trivial comment is about updating the contributing guide.

2025-01-18 03:35 UTC, agitter commented on .github/workflows/build-and-remove-template.yml
> +          context: ${{ inputs.context || inputs.path }}/.
I see, is this why we don't need a default context input?

2025-01-18 03:35 UTC, agitter commented on .github/workflows/build-containers.yml
> +    types: [opened, synchronize, reopened]
I checked options at https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request and these three look good. I'm still not sure what synchronize is even after looking at the docs.

2025-01-18 03:35 UTC, agitter commented on .github/workflows/test-spras.yml
> -      # can't be removed for some reason
Could transfer this comment to the new `docker rmi`

2025-01-18 03:35 UTC, agitter commented on .github/workflows/build-containers.yml
We will need to update Step 5 of the contribution guide to modify this workflow instead of `test-spras.yml`. Specifically the paragraph
> Extend .github/workflows/test-spras.yml to pull and build the new Docker image.

2025-01-18 03:35 UTC, agitter commented on .github/workflows/build-containers.yml
> +      tag: v2
I haven't been very thoughtful about which tags to test. Should we go back to testing latest for all of these?

2025-01-24 20:57 UTC, jhiemstrawisc commented on .github/workflows/build-and-remove-template.yml
> +      context:
The context lets Docker answer the question "where should I be scoped when if I need to start copying files from relative paths, as defined in the Dockerfile". For all the PRMs, the context should be set to the the same directory that holds the Dockerfile. However, building the SPRAS container requires that the context is set to the root of the repo so that the Dockerfile can copy everything it needs to.

The context isn't set as required because none of the PRM containers need to provide it (the default is simply the path to the PRM Dockerfile), but the SPRAS container passes the repo root as a context. See the `build-and-remove-spras` step from `build-containers.yml`.

2025-01-24 20:59 UTC, jhiemstrawisc commented on .github/workflows/build-containers.yml
> +    types: [opened, synchronize, reopened]
Agreed, they do a poor job of documenting it, but it basically means "whenever someone updates the PR":
https://github.com/orgs/community/discussions/24567

2025-01-24 21:01 UTC, jhiemstrawisc commented on .github/workflows/test-spras.yml
> -      # can't be removed for some reason
Addressed in a new commit.

2025-01-24 21:50 UTC, jhiemstrawisc commented on .github/workflows/build-containers.yml
> +      tag: v2
These tags are arbitrary -- they're set for the image that gets created in the action, but the image is immediately deleted and never pushed because all we're testing is that it builds. We could set the tags to anything we want! After reflecting a bit, I think I'll just remove the tag field as an input and always set things to latest.

2025-01-24 21:56 UTC, jhiemstrawisc commented on .github/workflows/build-containers.yml
Addressed in a recent commit.

2025-01-24 21:57 UTC, jhiemstrawisc commented on .github/workflows/build-containers.yml
> +    types: [opened, synchronize, reopened]
I removed the input in a recent commit.

2025-01-24 21:58 UTC, jhiemstrawisc commented on .github/workflows/build-and-remove-template.yml
> +          context: ${{ inputs.context || inputs.path }}/.
There's no sensible global default, since each context needs to be scoped to a specific directory. Every test must provide an input path, so I use that as a test-specific default.

2025-01-24 23:56 UTC, agitter reviewed
One more tag-related removal and then I'll merge

2025-01-24 23:56 UTC, agitter commented on .github/workflows/build-and-remove-template.yml
> +# - tag: The tag to be built.
```suggestion
```

2025-01-31 22:16 UTC, agitter approved these changes

2025-01-31 22:16 UTC, merged